# Generated by Django 4.2.13 on 2024-09-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newChat', '0004_alter_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='last_name', to='newChat.message'),
            preserve_default=False,
        ),
    ]
