# Generated by Django 4.2.13 on 2024-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newChat', '0006_alter_conversation_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='sent', max_length=255),
            preserve_default=False,
        ),
    ]
