# Generated by Django 4.2.13 on 2024-05-14 13:24

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimageuploadfragment',
            name='product',
        ),
        migrations.AddField(
            model_name='advertiserproduct',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_product_image_filename),
        ),
        migrations.AddField(
            model_name='advertiserproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_product_image_filename),
        ),
        migrations.AddField(
            model_name='advertiserproduct',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_product_image_filename),
        ),
        migrations.AddField(
            model_name='advertiserproduct',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_portfolio_image_filename),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_portfolio_image_filename),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.change_portfolio_image_filename),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='PortfolioImageUploadFragment',
        ),
        migrations.DeleteModel(
            name='ProductImageUploadFragment',
        ),
    ]
