# Generated by Django 4.2.13 on 2024-05-14 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_productimageuploadfragment_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiserproduct',
            name='id',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='id',
        ),
        migrations.AlterField(
            model_name='advertiserproduct',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
