# Generated by Django 4.2.13 on 2024-05-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_temp_id_advertiserproduct_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpaceForSpaceHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(choices=[('Print', 'Print'), ('Transportation', 'Transportation'), ('Event', 'Event'), ('Other', 'Other')], max_length=30)),
                ('url', models.URLField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_spaces', to='users.spacehost')),
            ],
        ),
    ]
