# Generated by Django 4.2.13 on 2024-05-22 17:34

from django.db import migrations, models


def migrate_languages(apps, schema_editor):
    SpaceHost = apps.get_model('users', 'SpaceHost')
    Language = apps.get_model('users', 'Language')

    for space_host in SpaceHost.objects.all():
        languages = Language.objects.filter(user=space_host).values_list('language', flat=True)
        space_host.languages_temp = ','.join(languages)
        space_host.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adspaceforspacehost'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacehost',
            name='languages_temp',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.RunPython(migrate_languages),
    ]
