# Generated by Django 4.2.13 on 2024-05-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240522_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacehost',
            old_name='languages_temp',
            new_name='languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
