# Generated by Django 4.2.13 on 2024-05-22 20:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_languages_temp_spacehost_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspaceforspacehost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=users.models.change_space_filename),
        ),
    ]
