# Generated by Django 4.2.13 on 2024-05-22 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_adspaceforspacehost_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspaceforspacehost',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
