# Generated by Django 4.2.13 on 2024-05-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_adspaceforspacehost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adspaceforspacehost',
            old_name='id',
            new_name='old_id',
        ),
    ]
