# Generated by Django 4.2.13 on 2024-05-22 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_adspaceforspacehost_old_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adspaceforspacehost',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='adspaceforspacehost',
            name='old_id',
        ),
    ]
