# Generated by Django 4.2.13 on 2024-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_temp_id_adspaceforspacehost_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adspaceforspacehost',
            name='space_type',
            field=models.CharField(choices=[('Print', 'Print'), ('Transportation', 'Transportation'), ('Event', 'Event'), ('Email', 'Email'), ('SMS', 'SMS'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='adspaceforspacehost',
            name='url',
            field=models.CharField(max_length=512),
        ),
    ]
