# Generated by Django 4.2.13 on 2024-09-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_platformbaseuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adspaceforspacehost',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
