# Generated by Django 4.2.13 on 2024-09-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_adspaceforspacehost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserproduct',
            name='productType',
            field=models.CharField(default='public', max_length=255),
            preserve_default=False,
        ),
    ]
