# Generated by Django 4.2.13 on 2024-09-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_reset_code_user_reset_code_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
