# Generated by Django 4.2.13 on 2024-10-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_affiliatelink_affiliatelinkvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatelink',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
